name: Build Debian Package

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set package version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION="1.0.0-dev+$(git rev-parse --short HEAD)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION"

      - name: Update version in control file
        run: |
          sed -i "s/^Version:.*/Version: ${{ steps.version.outputs.version }}/" debian/DEBIAN/control

      - name: Build Debian package (without image)
        run: make build
        
      - name: Rename package (without image)
        run: |
          mv swarm-cli_*.deb swarm-cli_${{ steps.version.outputs.version }}_all.deb

      - name: Build Debian package (with bundled image)
        run: make build-with-image
        
      - name: Rename package (with image)
        run: |
          mv swarm-cli_*.deb swarm-cli_${{ steps.version.outputs.version }}_all-with-image.deb

      - name: Upload Debian packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swarm-cli-deb-packages
          path: "*.deb"
          retention-days: 90

      - name: Create Release and Upload Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            swarm-cli_${{ steps.version.outputs.version }}_all.deb
            swarm-cli_${{ steps.version.outputs.version }}_all-with-image.deb
          draft: false
          prerelease: false
          body: |
            ## Swarm CLI Release ${{ steps.version.outputs.version }}
            
            ### Installation Options
            
            **Option 1: Lightweight package (recommended)**
            - Download: `swarm-cli_${{ steps.version.outputs.version }}_all.deb`
            - Size: ~10KB
            - Requires internet connection to pull Docker image on first use
            
            **Option 2: Self-contained package**
            - Download: `swarm-cli_${{ steps.version.outputs.version }}_all-with-image.deb`
            - Size: ~50-100MB
            - Includes bundled Docker image, no internet required
            - Perfect for offline/air-gapped environments
            
            ### Install
            ```bash
            # Download your preferred package
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/swarm-cli_${{ steps.version.outputs.version }}_all.deb
            
            # Install
            sudo apt install ./swarm-cli_${{ steps.version.outputs.version }}_all.deb
            ```
            
            ### Usage
            ```bash
            swarm-cli --help
            swarm-cli status
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
